services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["ng", "serve", "--host", "0.0.0.0", "--configuration", "docker-compose"]
    environment:
      NG_ALLOWED_HOSTS: localhost,127.0.0.1
    volumes:
      - ./src:/app/src
      - ./angular.json:/app/angular.json
    ports:
      - 4200:4200
