services:
  db:
    image: postgres:17.2
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=development
    volumes:
      - ./sql-init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8080:8080
