services:
  main-api:
    build:
      dockerfile: Dockerfile
      target: build
    command:
      [
        "dotnet",
        "watch",
        "--project",
        "ECommerce.Presentation",
        "--no-hot-reload",
        "--launch-profile",
        "http",
      ]
    ports:
      - 5042:8080
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      STRIPE_API_KEY: ${Stripe__ApiKey}
      STRIPE_WEBHOOK_SIGNATURE: ${Stripe__WebhookSignature}
      Master__Email: ${MainApi__Master__Email}
      Master__Password: ${MainApi__Master__Password}
      Database__Host: main-api-postgres
      Database__Port: 5432
      Database__Database: ${MainApi__Database__Database}
      Database__Username: ${MainApi__Database__Username}
      Database__Password: ${MainApi__Database__Password}
      MicroserviceNetworkConfig__PaymentServiceUrl: payment-service:8080
      Kafka__Servers: kafka:9092
    volumes:
      - ./MainApi:/app
      - /app/bin
      - /app/obj
    depends_on:
      main-api-postgres:
        condition: service_healthy
  main-api-postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${Database__Username}
      POSTGRES_PASSWORD: ${Database__Password}
      POSTGRES_DB: ${Database__Database}
    volumes:
      - ./sql-init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 10
      timeout: 10s
