apiVersion: batch/v1
kind: Job
metadata:
  name: myapp
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: umbrella
    meta.helm.sh/release-namespace: default
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - image: main-api-db-migrator:latest
          name: main-api-db-migrator
          imagePullPolicy: IfNotPresent
          env:
            - name: Database__Host
              value: postgres
            - name: Database__Port
              value: "5432"
            - name: Database__Password
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: Database__Password
