apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-api-deployment
  labels:
    app: main-api
spec:
  selector:
    matchLabels:
      app: main-api
  template:
    metadata:
      name: main-api-pod
      labels:
        app: main-api
    spec:
      containers:
        - image: main-api:latest
          name: main-api
          imagePullPolicy: IfNotPresent
          env:
            - name: Database__Host
              value: postgres
            - name: Database__Port
              value: "5432"
            - name: Database__Password
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: Database__Password
            - name: Master__Email
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: Master__Email
            - name: Master__Password
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: Master__Password
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: Kafka__Servers
              value: kafka:9092
            - name: STRIPE_API_KEY
              value: stripe
            - name: STRIPE_WEBHOOK_SIGNATURE
              value: secret
          resources:
            requests:
              cpu: "0.5"
              memory: "0.5Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
