include:
  - ./frontend/docker-compose.yml
  - ./BFF/docker-compose.yml
  - ./PaymentService/docker-compose.yml
  - ./ProductService/docker-compose.yml
  - ./StoreService/docker-compose.yml
  - ./UserService/docker-compose.yml
  - ./OrderService/docker-compose.yml
  - ./docker-compose-debug-tools.yml

services:
  init-kafka:
    image: bitnamilegacy/kafka:4.0.0
    entrypoint: ["/scripts/kafka-create-topics.sh"]
    volumes:
      - ./scripts/kafka-create-topics.sh:/scripts/kafka-create-topics.sh
  kafka:
    image: bitnamilegacy/kafka:4.0.0
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CLUSTER_ID: 1

      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9094"

      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CFG_LISTENERS: BROKER://:9092,CONTROLLER://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: BROKER://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      BITNAMI_DEBUG: yes
    ports:
      - 9092:9092
  reverse-proxy:
    image: nginx:1.29.1
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: on-failure
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    command: start-dev --hostname http://localhost:8080/auth --hostname-backchannel-dynamic true --proxy-headers xforwarded
    restart: on-failure
    environment:
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: password
        KC_BOOTSTRAP_ADMIN_USERNAME: admin
        KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - 9003:8080
    depends_on:
      - keycloak-postgres

  keycloak-postgres:
    image: postgres:17.4
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  keycloak-config:
    build:
      context: ./terraform/keycloak
      dockerfile: Dockerfile
    volumes:
      - ./terraform/keycloak:/workspace
    restart: on-failure

  data-seeder:
    build:
      context: ./DataSeeder
    restart: on-failure
    environment:
      API_BASE_URL: http://reverse-proxy
      KEYCLOAK_TOKEN_URL: http://keycloak:8080/realms/ecommerce-api/protocol/openid-connect/token
      KEYCLOAK_CLIENT_ID: ecommerce-api
      KEYCLOAK_CLIENT_SECRET: secret
      S3_ENDPOINT_URL: http://localstack:4566
      S3_BUCKET: ecommerce-resources
      AWS_DEFAULT_REGION: us-east-1
    volumes:
      - ./DataSeeder:/app
  localstack:
    container_name: '${LOCALSTACK_DOCKER_NAME:-localstack-main}'
    image: localstack/localstack
    ports:
      - '127.0.0.1:4566:4566' # LocalStack Gateway
      - '127.0.0.1:4510-4559:4510-4559' # external services port range
    environment:
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN}
      DEBUG: ${DEBUG:-0}
      PERSISTENCE: ${PERSISTENCE:-0}
      SERVICES: sts, iam, s3
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - '/var/run/docker.sock:/var/run/docker.sock'
  localstack-infra-init:
    build:
      context: terraform/aws
    restart: on-failure
    depends_on:
      - localstack
    environment:
      AWS_ENDPOINT_URL: http://localstack:4566
      S3_HOSTNAME: localstack      
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1