postgresql:
  auth:
    existingSecret: main-api-db-secret
    secretKeys:
      adminPasswordKey: Database__Password
  fullnameOverride: main-api-postgres
  primary:
    persistence:
      storageClass: standard
      size: 5Gi
      accessModes:
        - ReadWriteOnce