postgresql:
  auth:
    existingSecret: app-secrets
    secretKeys:
      adminPasswordKey: Database__Password
  fullnameOverride: postgres
  primary:
    persistence:
      storageClass: standard
      size: 5Gi
      accessModes:
        - ReadWriteOnce
    initdb:
      scriptsConfigMap: postgres-init
  volumePermissions:
    enabled: true

payment-service:
  Kafka__Servers: umbrella-kafka:9092

kafka:
  clusterId: 3f6c7185-aafc-4fc0-9431-e7295b3b1ec0
  broker:
    replicaCount: 2
    resources:
      requests:
        cpu: "2"
        memory: "6Gi"
      limits:
        cpu: "2"
        memory: "6Gi"
      